### ISSUE TITLE
broken by libsystemd -> systemd-libs? needs new release?

### ISSUE THREAD

**Issue by dradetsky** [archlinux/archlinux-docker#14]
I'm not 100% sure this is what's going on here, but it looks like it. A few days ago `pacman -Sy --noconfirm base-devel` worked, but now I get

```
:: systemd-libs and libsystemd are in conflict. Remove libsystemd? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: systemd-libs and libsystemd are in conflict
```

And you can't easily fix this because there's no `--assume-yes` flag for pacman, and `yes | pacman` doesn't work b/c you have to say 'all' or something first. It's possible that there's a solution using more low-level pacman config i'm not familiar with. But maybe you could just publish a new one?

**Comment by eli-schwartz** [comment]
> and `yes | pacman` doesn't work b/c you have to say 'all' or something first.

`pacman -Syu --noconfirm base-devel` would be the usual, recommended method of installing base-devel, because you don't want to do partial updates.

In this case, you'd split that into `yes y | pacman -Syu && pacman -S --noconfirm base-devel` so that the `yes` only applies to the `-Syu`.

...

Granted that updating the container is really preferable anyway.

**Comment by pierres** [comment]
I just released a new image anyway. Do you still have this issue?

**Comment by dradetsky** [comment]
no, it's all fixed
