### ISSUE TITLE
Support for other architectures?

### ISSUE THREAD

**Issue by samip5** [archlinux/archlinux-docker#25]
Where is the official base image for arm32 or arm64?

My images at https://hub.docker.com/r/samip537/archlinux/ are ~500MB for arm64, amd32 and amd64, but I think it would be better if the actual Archlinux maintainers would do the images.

My github repo: https://github.com/samip5/archlinux-docker

**Comment by znmeb** [comment]
I've got a couple of NVIDIA Jetson developer kits - a Nano and a Xavier AGX. They both have an L4T full Linux OS (Ubuntu bionic + NVIDIA drivers and applications) and the CPUs are `arm64v8`. They both have the NVIDIA container runtime so they're run any container that will work on an `arm64v8`. 

So I'm interested in getting an Arch Linux ARM image. Like @samip5 I'd prefer something "official" and "built automatically in the cloud".

**Comment by shibumi** [comment]
@samip5 We don't support anything other than amd64, because we have only amd64 packages in our repositories., The Arch Linux ARM projects exist, however they are a fully independent project.

Providing ARM images is not a technical one, it would be more a political project:

1. Do we want to support ARM?
2. Do we want to cooperate with Arch Linux ARM, if we don't want to provide these images by ourselves.
3. How would such a cooperation looks like?
4. Would it make sense to pull Arch Linux ARM into the official Arch Linux docker namespace? etc

My opinion is, that I would prefer a separate namespace for this like: `_/archlinuxarm`, because as mentioned, these projects are fully independent from each other.

**Comment by shibumi** [comment]
I am going to close this issue.. but feel free to further discuss this here. Maybe we could even get an Arch Linux ARM representative in here.

**Comment by znmeb** [comment]
I volunteered to help on the Arch Linux ARM forum for what it's worth - https://archlinuxarm.org/forum/viewtopic.php?f=9&t=14360#p63808
